name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_registries:
    name: Build Docker images and push them to ghcr.io and DockerHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Check out the repo 
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: frontend.Dockerfile
        push: true
        tags: |
          matandomuertos/server-homepage-frontend:latest
          ghcr.io/${{ github.repository }}/server-homepage-frontend:latest

    - name: Build and push backend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: backend.Dockerfile
        push: true
        tags: |
          matandomuertos/server-homepage-backend:latest
          ghcr.io/${{ github.repository }}/server-homepage-backend:latest